#!/bin/sh
#
# Copyright (c) 1992-2018 The FreeBSD Project. All rights reserved.
# Copyright (c) 2015-2018 Koichiro Iwao <meta@FreeBSD.org>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$
#
# REQUIRE: DAEMON
# PROVIDE: xrdp
#
# Add the following line to /etc/rc.conf to enable xrdp:
#
#  xrdp_enable="YES"
#  xrdp_sesman_enable="YES"

. /etc/rc.subr

name="xrdp"
rcvar="xrdp_enable"

load_rc_config "$name"
: ${xrdp_enable="NO"}

extra_commands="status allstart allstop allrestart keygen"
command="%%PREFIX%%/sbin/xrdp"

allstart_cmd="xrdp_allstart"
allstop_cmd="xrdp_allstop"
allrestart_cmd="xrdp_allrestart"
start_precmd="xrdp_precmd"
stop_postcmd="xrdp_poststop"
keygen_cmd="xrdp_generate_default_keys"

xrdp_allstart()
{
     run_rc_command "start"

    if checkyesno "xrdp_sesman_enable" && \
        ! %%PREFIX%%/etc/rc.d/xrdp-sesman forcestatus 1>/dev/null 2>&1; then
        %%PREFIX%%/etc/rc.d/xrdp-sesman start || return 1
    fi
}

xrdp_allstop()
{
    if checkyesno "xrdp_sesman_enable" && \
        %%PREFIX%%/etc/rc.d/xrdp-sesman forcestatus 1>/dev/null 2>&1; then
        %%PREFIX%%/etc/rc.d/xrdp-sesman stop || return 1
    fi

    run_rc_command "stop"
}

xrdp_allrestart()
{
    if checkyesno "xrdp_sesman_enable" && \
        %%PREFIX%%/etc/rc.d/xrdp-sesman forcestatus 1>/dev/null 2>&1; then
        %%PREFIX%%/etc/rc.d/xrdp-sesman restart || return 1
    fi

    run_rc_command "restart"
}

xrdp_poststop()
{
    # If running with dropped privileges, xrdp can't delete its own
    # PID file
    rm -f %%LOCALSTATEDIR%%/run/xrdp.pid
}

xrdp_precmd()
{
    run_rc_command "keygen"
}

xrdp_generate_default_keys()
{
    local rsakeys=rsakeys.ini
    local privatekey=key.pem
    local certificate=cert.pem
    local xrdp_user=_xrdp  # def. /usr/ports/UIDs
    local xrdp_group=_xrdp # def. /usr/ports/GIDs
    (
        cd %%PREFIX%%/etc/%%SYSCONFSUBDIR%% || exit 1

        umask 027

        [ -e "$rsakeys" ] || %%PREFIX%%/bin/xrdp-keygen xrdp "$rsakeys"
        [ -e "$privatekey" -a -e "$certificate" ] || \
            openssl req \
                -x509 \
                -newkey ed25519 \
                -noenc \
                -keyout "$privatekey" \
                -out "$certificate" \
                -days 1825 \
                -subj "/CN=$(hostname)" || exit 1

        # set group permission for the keys
        pw groupshow "$xrdp_group" >/dev/null 2>&1 && \
            for f in "$rsakeys" "$privatekey" "$certificate"
            do
                chown :"$xrdp_group" "$f"
                chmod g+r "$f"
            done
    )
}

run_rc_command "$1"
